require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe BandGenresController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # BandGenre. As you add validations to BandGenre, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BandGenresController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all band_genres as @band_genres" do
      band_genre = BandGenre.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:band_genres)).to eq([band_genre])
    end
  end

  describe "GET #show" do
    it "assigns the requested band_genre as @band_genre" do
      band_genre = BandGenre.create! valid_attributes
      get :show, params: {id: band_genre.to_param}, session: valid_session
      expect(assigns(:band_genre)).to eq(band_genre)
    end
  end

  describe "GET #new" do
    it "assigns a new band_genre as @band_genre" do
      get :new, params: {}, session: valid_session
      expect(assigns(:band_genre)).to be_a_new(BandGenre)
    end
  end

  describe "GET #edit" do
    it "assigns the requested band_genre as @band_genre" do
      band_genre = BandGenre.create! valid_attributes
      get :edit, params: {id: band_genre.to_param}, session: valid_session
      expect(assigns(:band_genre)).to eq(band_genre)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new BandGenre" do
        expect {
          post :create, params: {band_genre: valid_attributes}, session: valid_session
        }.to change(BandGenre, :count).by(1)
      end

      it "assigns a newly created band_genre as @band_genre" do
        post :create, params: {band_genre: valid_attributes}, session: valid_session
        expect(assigns(:band_genre)).to be_a(BandGenre)
        expect(assigns(:band_genre)).to be_persisted
      end

      it "redirects to the created band_genre" do
        post :create, params: {band_genre: valid_attributes}, session: valid_session
        expect(response).to redirect_to(BandGenre.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved band_genre as @band_genre" do
        post :create, params: {band_genre: invalid_attributes}, session: valid_session
        expect(assigns(:band_genre)).to be_a_new(BandGenre)
      end

      it "re-renders the 'new' template" do
        post :create, params: {band_genre: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested band_genre" do
        band_genre = BandGenre.create! valid_attributes
        put :update, params: {id: band_genre.to_param, band_genre: new_attributes}, session: valid_session
        band_genre.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested band_genre as @band_genre" do
        band_genre = BandGenre.create! valid_attributes
        put :update, params: {id: band_genre.to_param, band_genre: valid_attributes}, session: valid_session
        expect(assigns(:band_genre)).to eq(band_genre)
      end

      it "redirects to the band_genre" do
        band_genre = BandGenre.create! valid_attributes
        put :update, params: {id: band_genre.to_param, band_genre: valid_attributes}, session: valid_session
        expect(response).to redirect_to(band_genre)
      end
    end

    context "with invalid params" do
      it "assigns the band_genre as @band_genre" do
        band_genre = BandGenre.create! valid_attributes
        put :update, params: {id: band_genre.to_param, band_genre: invalid_attributes}, session: valid_session
        expect(assigns(:band_genre)).to eq(band_genre)
      end

      it "re-renders the 'edit' template" do
        band_genre = BandGenre.create! valid_attributes
        put :update, params: {id: band_genre.to_param, band_genre: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested band_genre" do
      band_genre = BandGenre.create! valid_attributes
      expect {
        delete :destroy, params: {id: band_genre.to_param}, session: valid_session
      }.to change(BandGenre, :count).by(-1)
    end

    it "redirects to the band_genres list" do
      band_genre = BandGenre.create! valid_attributes
      delete :destroy, params: {id: band_genre.to_param}, session: valid_session
      expect(response).to redirect_to(band_genres_url)
    end
  end

end
